{"name": "Система возвращает ошибку, если неправильно указать логин", "status": "passed", "steps": [{"name": "Логинимся", "status": "passed", "parameters": [{"name": "login", "value": "'invalid_login'"}, {"name": "password", "value": "'valid_password'"}], "start": 1739525484030, "stop": 1739525484245}], "start": 1739525484030, "stop": 1739525484246, "uuid": "c6ec0e3e-3f00-435b-8a56-41dc9e7d8acc", "historyId": "098c31939dfc5a0448c18624846e2e61", "testCaseId": "098c31939dfc5a0448c18624846e2e61", "fullName": "tests.tests_login.TestLogin#test_login_courier_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-5IUKQF9"}, {"name": "thread", "value": "11416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_login"}]}