{"name": "Система возвращает ошибку, если неправильно указать пароль", "status": "passed", "steps": [{"name": "Логинимся", "status": "passed", "parameters": [{"name": "login", "value": "'invalid_login'"}, {"name": "password", "value": "'valid_password'"}], "start": 1739802089831, "stop": 1739802090008}], "start": 1739802089830, "stop": 1739802090010, "uuid": "1f7850bb-14f9-4a54-8d32-920003d38e2e", "historyId": "e6812574981c1d02529bfd69aacf61a3", "testCaseId": "e6812574981c1d02529bfd69aacf61a3", "fullName": "tests.tests_login.TestLogin#test_password_courier_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-5IUKQF9"}, {"name": "thread", "value": "8952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_login"}]}